#!/usr/bin/env python3
"""Regenerate assets/fonts/mafa_charset.txt from the MAFA CHRONICLE UI
sources. The charset is the codepoint inventory for tools/gen_mafa_fonts.sh;
tests/test_mafa_ui_glyphs.py fails when UI copy and the charset drift apart,
so run this after every copy change and regenerate the fonts."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [
    ROOT / "main" / "mafa_app.c",
    ROOT / "main" / "mafa_view.c",
    ROOT / "main" / "mafa_model.c",
]
OUT = ROOT / "assets" / "fonts" / "mafa_charset.txt"

# CJK ideographs, full-width punctuation, and the UI symbols the copy uses
# (… ellipsis, ▶ cursor — geometric shapes). Everything matched here must be
# covered by the subset fonts, so extend only with glyphs the fonts carry.
CJK = re.compile(
    r"[\u2026\u25a0-\u25ff\u3000-\u303f\u3400-\u4dbf\u4e00-\u9fff\uff01-\uffee]"
)

chars = set()
for src in SOURCES:
    chars.update(CJK.findall(src.read_text(encoding="utf-8")))

OUT.write_text(
    "# MAFA CHRONICLE UI CJK charset — generated by tools/gen_mafa_charset.py\n"
    "# from main/mafa_{app,view,model}.c. ASCII (0x20-0x7E) is added by the\n"
    "# generator separately. Do not hand-edit; regenerate instead.\n"
    + "".join(sorted(chars))
    + "\n",
    encoding="utf-8",
)
print(f"wrote {OUT.relative_to(ROOT)} ({len(chars)} codepoints)")
