#!/usr/bin/env bash
# Regenerate the MAFA CHRONICLE application CJK subset fonts
# (PRD_MAFA_CHRONICLE 11; same Plan B pattern as FOG MARCH 10.4).
#
# Inputs (this script is the version-controlled record of the conversion):
#   assets/fonts/SourceHanSansSC-Regular.otf  (NOT tracked; download noted in
#     tools/gen_fog_march_fonts.sh — same font file, SIL OFL 1.1)
#   assets/fonts/mafa_charset.txt  (tracked; generated by
#     tools/gen_mafa_charset.py from the UI sources)
#
# Outputs (tracked, compiled by main/CMakeLists.txt):
#   assets/fonts/mafa_font_16.c  -- body text
#   assets/fonts/mafa_font_20.c  -- titles
#
# Requirements: Node.js (npx) and network access to the npm registry.
# Usage: python tools/gen_mafa_charset.py && bash tools/gen_mafa_fonts.sh
set -euo pipefail
cd "$(dirname "$0")/.."

FONT=assets/fonts/SourceHanSansSC-Regular.otf
CHARSET=assets/fonts/mafa_charset.txt
LV_FONT_CONV_VERSION=1.5.3

test -f "$FONT" || {
    echo "missing $FONT" >&2
    echo "download it per tools/gen_fog_march_fonts.sh header" >&2
    exit 1
}

# Printable ASCII always rides along; the CJK part is the generated charset.
SYMBOLS=$(grep -v '^[[:space:]]*#' "$CHARSET" | tr -d ' \t\r\n')

for size in 16 20; do
    npx --yes "lv_font_conv@${LV_FONT_CONV_VERSION}" \
        --font "$FONT" \
        --size "$size" --bpp 4 --format lvgl --no-compress \
        --range 0x20-0x7E \
        --symbols "$SYMBOLS" \
        --lv-font-name "mafa_font_${size}" --lv-include lvgl.h \
        --output "assets/fonts/mafa_font_${size}.c"
    echo "wrote assets/fonts/mafa_font_${size}.c"
done
